import random

REASONING_BANK = {
    "Easy": [
        {"question": "Find the odd one out: Apple, Banana, Dog, Orange", "options": ["Apple", "Banana", "Dog", "Orange"], "answer": "Dog"},
        {"question": "Find the odd one out: Car, Bus, Train, Tree", "options": ["Car", "Bus", "Train", "Tree"], "answer": "Tree"},
        {"question": "Look at the pattern: ☀️, 🌙, ☀️, 🌙, _. What comes next?", "options": ["☀️", "🌙", "⭐", "☁️"], "answer": "☀️"},
        {"question": "Find the odd one out: Red, Blue, Happy, Green", "options": ["Red", "Blue", "Happy", "Green"], "answer": "Happy"},
        {"question": "Look at the pattern: △, ◯, △, ◯, _. What comes next?", "options": ["△", "◯", "◻", "⭐"], "answer": "△"},
        {"question": "Find the odd one out: Cat, Dog, Bird, Chair", "options": ["Cat", "Dog", "Bird", "Chair"], "answer": "Chair"},
        {"question": "Look at the sequence: A, B, C, D, _. What is the next letter?", "options": ["E", "F", "G", "H"], "answer": "E"},
        {"question": "Find the odd one out: Shoe, Sock, Hat, Pizza", "options": ["Shoe", "Sock", "Hat", "Pizza"], "answer": "Pizza"},
        {"question": "Look at the pattern: 1, 2, 1, 2, _. What comes next?", "options": ["1", "2", "3", "4"], "answer": "1"},
        {"question": "Find the odd one out: 1, 2, 3, A", "options": ["1", "2", "3", "A"], "answer": "A"},
        {"question": "Look at the sequence: 10, 9, 8, 7, _. What comes next?", "options": ["4", "5", "6", "7"], "answer": "6"},
        {"question": "Find the odd one out: Sun, Moon, Star, Book", "options": ["Sun", "Moon", "Star", "Book"], "answer": "Book"},
        {"question": "Look at the pattern: 🔴, 🔵, 🔴, 🔵, _. What comes next?", "options": ["🔴", "🔵", "🟡", "🟢"], "answer": "🔴"},
        {"question": "Find the odd one out: Eye, Ear, Nose, Pencil", "options": ["Eye", "Ear", "Nose", "Pencil"], "answer": "Pencil"},
        {"question": "If today is Monday, what day is tomorrow?", "options": ["Sunday", "Tuesday", "Wednesday", "Friday"], "answer": "Tuesday"},
        {"question": "Look at the sequence: 2, 4, 6, _. What comes next?", "options": ["7", "8", "9", "10"], "answer": "8"},
        {"question": "Find the odd one out: Milk, Juice, Water, Sand", "options": ["Milk", "Juice", "Water", "Sand"], "answer": "Sand"},
        {"question": "Which is the tallest? Ant, Dog, Giraffe, Cat", "options": ["Ant", "Dog", "Giraffe", "Cat"], "answer": "Giraffe"},
        {"question": "Look at the pattern: 👍, 👎, 👍, 👎, _. What comes next?", "options": ["👍", "👎", "👏", "👋"], "answer": "👍"},
        {"question": "Find the odd one out: Happy, Sad, Angry, Table", "options": ["Happy", "Sad", "Angry", "Table"], "answer": "Table"},
        {"question": "What number is missing? 1, 3, _, 7, 9", "options": ["2", "4", "5", "6"], "answer": "5"},
        {"question": "Find the odd one out: Shirt, Pants, Jacket, Apple", "options": ["Shirt", "Pants", "Jacket", "Apple"], "answer": "Apple"},
        {"question": "If a bird flies, a fish _____?", "options": ["Walks", "Runs", "Swims", "Jumps"], "answer": "Swims"},
        {"question": "Look at the sequence: a, b, c, d, _. What comes next?", "options": ["e", "f", "x", "y"], "answer": "e"},
        {"question": "Find the odd one out: Spoon, Fork, Knife, Shoe", "options": ["Spoon", "Fork", "Knife", "Shoe"], "answer": "Shoe"},
        {"question": "Which animal is bigger? Mouse, Cat, Dog, Elephant", "options": ["Mouse", "Cat", "Dog", "Elephant"], "answer": "Elephant"},
        {"question": "Look at the pattern: ⭐, ☁️, ⭐, ☁️, _. What comes next?", "options": ["⭐", "☁️", "☀️", "🌙"], "answer": "⭐"},
        {"question": "Find the odd one out: Pen, Pencil, Crayon, Milk", "options": ["Pen", "Pencil", "Crayon", "Milk"], "answer": "Milk"},
        {"question": "If ice is cold, fire is _____?", "options": ["Cold", "Warm", "Hot", "Freezing"], "answer": "Hot"},
        {"question": "Look at the sequence: 10, 20, 30, _. What comes next?", "options": ["35", "40", "45", "50"], "answer": "40"},
        {"question": "Find the odd one out: Monday, Tuesday, January, Friday", "options": ["Monday", "Tuesday", "January", "Friday"], "answer": "January"},
        {"question": "Which vehicle has 2 wheels?", "options": ["Car", "Bus", "Bicycle", "Truck"], "answer": "Bicycle"},
        {"question": "Look at the pattern: ⬆️, ⬇️, ⬆️, ⬇️, _. What comes next?", "options": ["⬆️", "⬇️", "➡️", "⬅️"], "answer": "⬆️"},
        {"question": "Find the odd one out: Circle, Square, Triangle, Red", "options": ["Circle", "Square", "Triangle", "Red"], "answer": "Red"},
        {"question": "If sugar is sweet, lemon is _____?", "options": ["Sweet", "Salty", "Spicy", "Sour"], "answer": "Sour"},
        {"question": "Look at the sequence: z, y, x, _. What comes next?", "options": ["a", "b", "w", "v"], "answer": "w"},
        {"question": "Find the odd one out: Piano, Guitar, Drum, House", "options": ["Piano", "Guitar", "Drum", "House"], "answer": "House"},
        {"question": "Which of these is a fruit?", "options": ["Potato", "Carrot", "Apple", "Onion"], "answer": "Apple"},
        {"question": "Look at the pattern: 11, 22, 11, 22, _. What comes next?", "options": ["11", "22", "33", "44"], "answer": "11"},
        {"question": "Find the odd one out: Spring, Summer, Winter, Rain", "options": ["Spring", "Summer", "Winter", "Rain"], "answer": "Rain"},
        {"question": "If a dog has 4 legs, a spider has _____ legs?", "options": ["4", "6", "8", "10"], "answer": "8"},
        {"question": "Look at the sequence: 5, 10, 15, _. What comes next?", "options": ["16", "20", "25", "30"], "answer": "20"},
        {"question": "Find the odd one out: Tiger, Lion, Bear, Toy", "options": ["Tiger", "Lion", "Bear", "Toy"], "answer": "Toy"},
        {"question": "Which is the smallest? House, Car, Ant, Tree", "options": ["House", "Car", "Ant", "Tree"], "answer": "Ant"},
        {"question": "Look at the pattern: 🟢, 🟢, 🔴, 🟢, 🟢, _. What comes next?", "options": ["🟢", "🔴", "🟡", "🔵"], "answer": "🔴"},
        {"question": "Find the odd one out: Sister, Brother, Mother, Friend", "options": ["Sister", "Brother", "Mother", "Friend"], "answer": "Friend"},
        {"question": "If a rock is hard, a pillow is _____?", "options": ["Soft", "Hard", "Heavy", "Loud"], "answer": "Soft"},
        {"question": "Look at the sequence: 100, 99, 98, _. What comes next?", "options": ["95", "96", "97", "98"], "answer": "97"},
        {"question": "Find the odd one out: Tree, Flower, Grass, Car", "options": ["Tree", "Flower", "Grass", "Car"], "answer": "Car"},
        {"question": "Which animal says 'Moo'?", "options": ["Dog", "Cat", "Cow", "Sheep"], "answer": "Cow"}
    ],
    "Medium": [
        {"question": "If CAT is coded as 3-1-20, how is DOG coded? (A=1, B=2, C=3...)", "options": ["4-15-7", "3-15-6", "4-14-6", "5-15-7"], "answer": "4-15-7"},
        {"question": "Find the odd one out: Tomato, Carrot, Potato, Onion (Hint: where do they grow?)", "options": ["Tomato", "Carrot", "Potato", "Onion"], "answer": "Tomato"},
        {"question": "Look at the pattern: A, C, E, G, _. What comes next?", "options": ["H", "I", "J", "K"], "answer": "I"},
        {"question": "If a puzzle has 50 pieces and you put 30 together, how many are left?", "options": ["10", "15", "20", "25"], "answer": "20"},
        {"question": "Find the missing number: 2, 5, 8, 11, _", "options": ["12", "13", "14", "15"], "answer": "14"},
        {"question": "If yesterday was Tuesday, what day is tomorrow?", "options": ["Wednesday", "Thursday", "Friday", "Monday"], "answer": "Thursday"},
        {"question": "Find the odd one out: Square, Rectangle, Circle, Triangle (Hint: corners)", "options": ["Square", "Rectangle", "Circle", "Triangle"], "answer": "Circle"},
        {"question": "Look at the pattern: 🟩, 🟨, 🟥, 🟩, 🟨, _. What comes next?", "options": ["🟩", "🟨", "🟥", "🟦"], "answer": "🟥"},
        {"question": "Which word doesn't belong? Fast, Quick, Rapid, Slow", "options": ["Fast", "Quick", "Rapid", "Slow"], "answer": "Slow"},
        {"question": "Find the sequence: 20, 18, 16, 14, _", "options": ["10", "11", "12", "13"], "answer": "12"},
        {"question": "If you are facing North and turn right, which way are you facing?", "options": ["East", "West", "South", "North"], "answer": "East"},
        {"question": "Find the odd one out: Airplane, Helicopter, Bird, Submarine", "options": ["Airplane", "Helicopter", "Bird", "Submarine"], "answer": "Submarine"},
        {"question": "Look at the pattern: M, O, Q, S, _. What comes next?", "options": ["T", "U", "V", "W"], "answer": "U"},
        {"question": "If breakfast is in the morning, dinner is in the _____?", "options": ["Morning", "Afternoon", "Evening", "Night"], "answer": "Evening"},
        {"question": "Find the missing number: 50, 40, 30, _, 10", "options": ["15", "20", "25", "35"], "answer": "20"},
        {"question": "Which word doesn't belong? Big, Large, Huge, Tiny", "options": ["Big", "Large", "Huge", "Tiny"], "answer": "Tiny"},
        {"question": "If RED is 3 letters, BLUE is 4 letters, YELLOW is _____ letters?", "options": ["5", "6", "7", "8"], "answer": "6"},
        {"question": "Find the odd one out: Eyes, Ears, Nose, Fingers", "options": ["Eyes", "Ears", "Nose", "Fingers"], "answer": "Fingers"},
        {"question": "Look at the pattern: 1A, 2B, 3C, _. What comes next?", "options": ["4C", "4D", "5D", "3D"], "answer": "4D"},
        {"question": "If an hour has 60 minutes, half an hour has _____ minutes?", "options": ["15", "20", "30", "45"], "answer": "30"},
        {"question": "Find the odd one out: Winter, Summer, Cold, Spring", "options": ["Winter", "Summer", "Cold", "Spring"], "answer": "Cold"},
        {"question": "Look at the sequence: 3, 6, 9, 12, _", "options": ["13", "14", "15", "16"], "answer": "15"},
        {"question": "If a square has 4 sides, a hexagon has _____ sides?", "options": ["5", "6", "7", "8"], "answer": "6"},
        {"question": "Find the odd one out: Book, Magazine, Newspaper, Television", "options": ["Book", "Magazine", "Newspaper", "Television"], "answer": "Television"},
        {"question": "Look at the pattern: Z, Y, X, W, _. What comes next?", "options": ["V", "U", "T", "S"], "answer": "V"},
        {"question": "Which letter is midway between A and E in the alphabet?", "options": ["B", "C", "D", "F"], "answer": "C"},
        {"question": "Find the missing number: 1, 4, 7, 10, _", "options": ["11", "12", "13", "14"], "answer": "13"},
        {"question": "Find the odd one out: Cup, Glass, Mug, Plate", "options": ["Cup", "Glass", "Mug", "Plate"], "answer": "Plate"},
        {"question": "If you cut an apple in half, how many pieces do you have?", "options": ["1", "2", "3", "4"], "answer": "2"},
        {"question": "Look at the pattern: 10, 15, 20, 25, _. What comes next?", "options": ["28", "30", "32", "35"], "answer": "30"},
        {"question": "Which word doesn't belong? Run, Sprint, Jog, Sleep", "options": ["Run", "Sprint", "Jog", "Sleep"], "answer": "Sleep"},
        {"question": "If tomorrow is Sunday, what was yesterday?", "options": ["Thursday", "Friday", "Saturday", "Monday"], "answer": "Friday"},
        {"question": "Find the odd one out: Guitar, Violin, Drums, Cello", "options": ["Guitar", "Violin", "Drums", "Cello"], "answer": "Drums"},
        {"question": "Look at the pattern: △, △, ◯, △, △, _. What comes next?", "options": ["△", "◯", "◻", "⭐"], "answer": "◯"},
        {"question": "What is the 5th letter of the alphabet?", "options": ["D", "E", "F", "G"], "answer": "E"},
        {"question": "Find the odd one out: North, East, Left, West", "options": ["North", "East", "Left", "West"], "answer": "Left"},
        {"question": "If you have 2 feet, how many toes do you have in total?", "options": ["5", "10", "15", "20"], "answer": "10"},
        {"question": "Look at the sequence: 100, 90, 80, 70, _", "options": ["50", "60", "65", "75"], "answer": "60"},
        {"question": "Which animal does not lay eggs?", "options": ["Chicken", "Duck", "Snake", "Dog"], "answer": "Dog"},
        {"question": "Find the odd one out: Sad, Crying, Unhappy, Laughing", "options": ["Sad", "Crying", "Unhappy", "Laughing"], "answer": "Laughing"},
        {"question": "If 1 represents A, 2 represents B... what represents E?", "options": ["3", "4", "5", "6"], "answer": "5"},
        {"question": "Look at the pattern: 🌑, 🌓, 🌕, 🌑, 🌓, _. What comes next?", "options": ["🌑", "🌓", "🌕", "☀️"], "answer": "🌕"},
        {"question": "Find the missing number: 7, 7, 8, 8, 9, _", "options": ["8", "9", "10", "11"], "answer": "9"},
        {"question": "Find the odd one out: Rain, Snow, Hail, Sun", "options": ["Rain", "Snow", "Hail", "Sun"], "answer": "Sun"},
        {"question": "How many days are in a single week?", "options": ["5", "6", "7", "8"], "answer": "7"},
        {"question": "Look at the pattern: A1, B2, C3, _. What comes next?", "options": ["D3", "D4", "C4", "E5"], "answer": "D4"},
        {"question": "Which of these is the heaviest?", "options": ["Feather", "Pencil", "Book", "Car"], "answer": "Car"},
        {"question": "Find the odd one out: Dollar, Coin, Note, Tree", "options": ["Dollar", "Coin", "Note", "Tree"], "answer": "Tree"},
        {"question": "If A is first and Z is last, what is M?", "options": ["Second", "Middle", "End", "Third"], "answer": "Middle"},
        {"question": "Look at the sequence: 1, 2, 4, 8, _ (Hint: double each number)", "options": ["10", "12", "14", "16"], "answer": "16"}
    ],
    "Hard": [
        {"question": "If 2 cats can catch 2 mice in 2 minutes, how many cats are needed to catch 10 mice in 10 minutes?", "options": ["2", "5", "10", "20"], "answer": "2"},
        {"question": "Look at the sequence: 1, 1, 2, 3, 5, 8, _. What comes next?", "options": ["10", "11", "12", "13"], "answer": "13"},
        {"question": "Find the odd one out: Mercury, Earth, Sun, Jupiter", "options": ["Mercury", "Earth", "Sun", "Jupiter"], "answer": "Sun"},
        {"question": "If you read the word 'RACECAR' backwards, what does it say?", "options": ["CAR", "RACE", "RACECAR", "RACEAC"], "answer": "RACECAR"},
        {"question": "What number is the same upside down as it is right side up?", "options": ["6", "8", "9", "3"], "answer": "8"},
        {"question": "Look at the pattern: 2, 6, 18, 54, _. What comes next?", "options": ["108", "162", "200", "216"], "answer": "162"},
        {"question": "Which of these words has the same number of vowels and consonants? 'TEAM'", "options": ["Yes", "No", "Sometimes", "Maybe"], "answer": "Yes"},
        {"question": "Find the missing number in the grid puzzle (if top row is 2, 4, 6 and bottom row is 3, 6, _)", "options": ["7", "8", "9", "10"], "answer": "9"},
        {"question": "I am an odd number. Take away a letter and I become even. What number am I?", "options": ["Seven", "Three", "Nine", "Five"], "answer": "Seven"},
        {"question": "Look at the sequence: Z, W, T, Q, _. What comes next? (Hint: skip 2 letters backward)", "options": ["O", "N", "M", "P"], "answer": "N"},
        {"question": "Find the odd one out: Circle, Sphere, Cylinder, Triangle", "options": ["Circle", "Sphere", "Cylinder", "Triangle"], "answer": "Triangle"},
        {"question": "If a clock shows 3:00, what angle do the hands make?", "options": ["45 degrees", "90 degrees", "180 degrees", "0 degrees"], "answer": "90 degrees"},
        {"question": "Look at the pattern: 1, 4, 9, 16, _. What comes next? (Hint: squares)", "options": ["20", "24", "25", "30"], "answer": "25"},
        {"question": "Which is correct? 'The yolk of the egg IS white' or 'The yolk of the egg ARE white'?", "options": ["IS", "ARE", "Neither (yolks are yellow)", "Both"], "answer": "Neither (yolks are yellow)"},
        {"question": "Find the sequence: 5, 11, 23, 47, _ (Hint: x2 + 1)", "options": ["85", "90", "94", "95"], "answer": "95"},
        {"question": "How many months have 28 days?", "options": ["1", "6", "11", "All 12"], "answer": "All 12"},
        {"question": "If a doctor gives you 3 pills and tells you to take 1 every half hour, how long will they last?", "options": ["30 mins", "1 hour", "1.5 hours", "2 hours"], "answer": "1 hour"},
        {"question": "Look at the pattern: 10, 9, 7, 4, _. What comes next?", "options": ["0", "1", "2", "3"], "answer": "0"},
        {"question": "Which word is spelled incorrectly in the dictionary?", "options": ["Wrong", "Incorrectly", "Right", "Mistake"], "answer": "Incorrectly"},
        {"question": "Find the odd one out: Ostrich, Penguin, Kiwi, Eagle", "options": ["Ostrich", "Penguin", "Kiwi", "Eagle"], "answer": "Eagle"},
        {"question": "If A=1, B=2... what does C+D equal?", "options": ["5", "6", "7", "8"], "answer": "7"},
        {"question": "What belongs to you, but others use it more than you?", "options": ["Your clothes", "Your name", "Your house", "Your shoes"], "answer": "Your name"},
        {"question": "Look at the sequence: 100, 50, 25, _. What comes next?", "options": ["10", "12.5", "15", "20"], "answer": "12.5"},
        {"question": "Find the missing number: 1, 2, 6, 24, _ (Hint: multiply by 2, 3, 4, 5)", "options": ["60", "90", "100", "120"], "answer": "120"},
        {"question": "What has hands but cannot clap?", "options": ["A tree", "A body", "A clock", "A desk"], "answer": "A clock"},
        {"question": "Look at the pattern: J, F, M, A, M, _. What comes next? (Hint: months)", "options": ["A", "J", "S", "O"], "answer": "J"},
        {"question": "Find the odd one out: Iron, Copper, Silver, Wood", "options": ["Iron", "Copper", "Silver", "Wood"], "answer": "Wood"},
        {"question": "Which word can have its first letter removed and still sound the same? (Empty)", "options": ["Empty", "Full", "Clear", "Blind"], "answer": "Empty"},
        {"question": "Look at the sequence: 2, 3, 5, 7, 11, _ (Hint: prime numbers)", "options": ["12", "13", "14", "15"], "answer": "13"},
        {"question": "What has keys but can't open locks?", "options": ["A piano", "A map", "A safe", "A door"], "answer": "A piano"},
        {"question": "Find the odd one out: Triangle, Square, Pentagon, Hexagon, Circle", "options": ["Square", "Pentagon", "Hexagon", "Circle"], "answer": "Circle"},
        {"question": "If you multiply this number by any other number, the answer is always the same. What is it?", "options": ["1", "0", "10", "2"], "answer": "0"},
        {"question": "Look at the pattern: 21, 20, 18, 15, 11, _. What comes next?", "options": ["5", "6", "7", "8"], "answer": "6"},
        {"question": "What starts with T, ends with T, and has T in it?", "options": ["Tent", "Test", "Teapot", "Taint"], "answer": "Teapot"},
        {"question": "Find the missing letter: O, T, T, F, F, S, S, E, _ (Hint: numbers)", "options": ["N", "T", "E", "S"], "answer": "N"},
        {"question": "Which of these weighs the most: A pound of feathers or a pound of rocks?", "options": ["Feathers", "Rocks", "They weigh the same", "It depends"], "answer": "They weigh the same"},
        {"question": "Look at the sequence: 10, 11, 13, 16, 20, _. What comes next?", "options": ["24", "25", "26", "27"], "answer": "25"},
        {"question": "I have branches, but no fruit, trunk or leaves. What am I?", "options": ["A tree", "A river", "A bank", "A map"], "answer": "A bank"},
        {"question": "Find the odd one out: 2, 4, 6, 8, 9", "options": ["2", "4", "6", "9"], "answer": "9"},
        {"question": "What comes once in a minute, twice in a moment, but never in a thousand years?", "options": ["The letter M", "The letter T", "A clock", "A second"], "answer": "The letter M"},
        {"question": "Look at the pattern: M, T, W, T, F, _. What comes next? (Hint: days)", "options": ["M", "T", "S", "W"], "answer": "S"},
        {"question": "If you drop a yellow hat in the Red Sea, what does it become?", "options": ["Red", "Orange", "Wet", "Salty"], "answer": "Wet"},
        {"question": "Find the missing number: 8, 27, 64, _ (Hint: cubes)", "options": ["100", "121", "125", "144"], "answer": "125"},
        {"question": "I am tall when I'm young, and I'm short when I'm old. What am I?", "options": ["A human", "A tree", "A candle", "A pencil"], "answer": "A candle"},
        {"question": "Look at the sequence: 1, 3, 7, 15, _ (Hint: x2 + 1)", "options": ["28", "30", "31", "33"], "answer": "31"},
        {"question": "What has a neck but no head?", "options": ["A shirt", "A bottle", "A giraffe", "A dog"], "answer": "A bottle"},
        {"question": "Find the odd one out: Carrot, Radish, Potato, Apple", "options": ["Carrot", "Radish", "Potato", "Apple"], "answer": "Apple"},
        {"question": "The more you take, the more you leave behind. What are they?", "options": ["Memories", "Footsteps", "Money", "Time"], "answer": "Footsteps"},
        {"question": "Look at the pattern: Z, X, V, T, _. What comes next? (Hint: skip 1 letter)", "options": ["S", "R", "Q", "P"], "answer": "R"},
        {"question": "What breaks yet never falls, and what falls yet never breaks?", "options": ["Glass and water", "Day and night", "Wood and leaves", "Heart and head"], "answer": "Day and night"}
    ]
}

def get_reasoning_questions(level, count=10):
    if level not in REASONING_BANK:
        return []
    questions = random.sample(REASONING_BANK[level], min(count, len(REASONING_BANK[level])))
    for q in questions:
        random.shuffle(q["options"])
    return questions
