import random

# Format: (Word, Correct, Wrong1, Wrong2, Wrong3, Example sentence)
EASY_WORDS = [
    ("Happy", "Joyful", "Sad", "Angry", "Tired", "He was joyful when he got a new puppy."),
    ("Big", "Large", "Small", "Tiny", "Short", "The elephant is a very large animal."),
    ("Small", "Little", "Huge", "Giant", "Tall", "She found a little beetle on the leaf."),
    ("Fast", "Quick", "Slow", "Lazy", "Still", "The quick cheetah caught its prey."),
    ("Slow", "Sluggish", "Fast", "Rapid", "Swift", "The sluggish turtle slowly crossed the road."),
    ("Good", "Excellent", "Bad", "Awful", "Poor", "You did an excellent job on your drawing."),
    ("Bad", "Terrible", "Great", "Super", "Good", "The terrible storm knocked down the trees."),
    ("Hot", "Warm", "Cold", "Freezing", "Cool", "The warm soup felt nice on a cold day."),
    ("Cold", "Chilly", "Hot", "Boiling", "Warm", "The chilly wind made me put on a coat."),
    ("Funny", "Hilarious", "Serious", "Sad", "Boring", "The clown was hilarious at the party."),
    ("Sad", "Unhappy", "Glad", "Cheerful", "Joyful", "He felt unhappy when his toy broke."),
    ("Smart", "Clever", "Silly", "Dumb", "Foolish", "The clever girl solved the puzzle quickly."),
    ("Silly", "Goofy", "Serious", "Smart", "Brave", "The goofy puppy chased its own tail."),
    ("Brave", "Courageous", "Afraid", "Scared", "Fearful", "The courageous knight fought the dragon."),
    ("Scared", "Frightened", "Brave", "Bold", "Fearless", "The frightened cat hid under the bed."),
    ("Strong", "Powerful", "Weak", "Frail", "Fragile", "The powerful horse pulled the heavy cart."),
    ("Weak", "Frail", "Strong", "Tough", "Sturdy", "The frail bird needed help to fly."),
    ("Loud", "Noisy", "Quiet", "Silent", "Peaceful", "The noisy parade marched down the street."),
    ("Quiet", "Silent", "Loud", "Noisy", "Wild", "The silent library was a good place to read."),
    ("Pretty", "Beautiful", "Ugly", "Plain", "Messy", "She wore a beautiful dress to the party."),
    ("Ugly", "Hideous", "Pretty", "Lovely", "Cute", "The hideous monster was just wearing a mask."),
    ("Clean", "Tidy", "Dirty", "Messy", "Muddy", "Her bedroom was tidy after she picked up her toys."),
    ("Dirty", "Messy", "Clean", "Neat", "Spotless", "His clothes were messy after playing in the mud."),
    ("Hard", "Difficult", "Easy", "Simple", "Soft", "The difficult puzzle took hours to finish."),
    ("Easy", "Simple", "Hard", "Complex", "Tough", "The simple math problem just took a second."),
    ("Soft", "Smooth", "Rough", "Hard", "Bumpy", "The smooth blanket felt nice and cozy."),
    ("Rough", "Bumpy", "Soft", "Smooth", "Flat", "The bumpy road made the car shake."),
    ("Wet", "Damp", "Dry", "Parched", "Thirsty", "The damp towel needed to be dried."),
    ("Dry", "Parched", "Wet", "Soaked", "Damp", "The parched desert rarely sees rain."),
    ("Bright", "Shiny", "Dark", "Dim", "Dull", "The shiny star sparkled in the night sky."),
    ("Dark", "Dim", "Bright", "Light", "Shiny", "The dim room was hard to read in."),
    ("Tall", "High", "Short", "Low", "Tiny", "The high tower reached into the clouds."),
    ("Short", "Brief", "Tall", "Long", "High", "The brief meeting was over in five minutes."),
    ("Long", "Extended", "Short", "Brief", "Small", "The extended vacation lasted for three weeks."),
    ("Old", "Ancient", "New", "Modern", "Young", "The ancient ruins were thousands of years old."),
    ("New", "Recent", "Old", "Used", "Worn", "The recent movie just came out yesterday."),
    ("Rich", "Wealthy", "Poor", "Broke", "Needy", "The wealthy king had a lot of gold."),
    ("Poor", "Needy", "Rich", "Wealthy", "Affluent", "The needy family received help from the community."),
    ("Right", "Correct", "Wrong", "False", "Incorrect", "She gave the correct answer to the question."),
    ("Wrong", "Incorrect", "Right", "True", "Correct", "He realized his answer was incorrect."),
    ("True", "Real", "False", "Fake", "Pretend", "The real story was better than the movie."),
    ("False", "Fake", "True", "Real", "Genuine", "The fake diamond was made of glass."),
    ("Near", "Close", "Far", "Distant", "Away", "The close friends lived next door to each other."),
    ("Far", "Distant", "Near", "Close", "Nearby", "The distant mountains looked purple in the sunset."),
    ("Early", "Premature", "Late", "Delayed", "Tardy", "The premature baby was born a month early."),
    ("Late", "Tardy", "Early", "Prompt", "Punctual", "The tardy student missed the first bell."),
    ("Full", "Packed", "Empty", "Blank", "Bare", "The packed stadium was cheering for the home team."),
    ("Empty", "Bare", "Full", "Packed", "Crowded", "The bare walls needed some paintings."),
    ("Glad", "Happy", "Mad", "Sad", "Tired", "I am happy to see you today."),
    ("Mad", "Angry", "Glad", "Joyful", "Happy", "He was angry when he lost his favorite toy.")
]

MEDIUM_WORDS = [
    ("Begin", "Commence", "End", "Finish", "Stop", "The ceremony will commence at noon."),
    ("End", "Conclude", "Begin", "Start", "Open", "We will conclude the meeting with a vote."),
    ("Assist", "Help", "Hinder", "Harm", "Block", "Can you help me carry these boxes?"),
    ("Hinder", "Block", "Assist", "Help", "Aid", "The fallen tree will block the road."),
    ("Construct", "Build", "Destroy", "Ruin", "Break", "They will build a new school here."),
    ("Destroy", "Ruin", "Construct", "Create", "Build", "The storm could ruin the crops."),
    ("Detect", "Discover", "Hide", "Miss", "Ignore", "Scientists discover new things every day."),
    ("Hide", "Conceal", "Detect", "Reveal", "Show", "He tried to conceal his surprise."),
    ("Enormous", "Gigantic", "Tiny", "Miniature", "Small", "The gigantic whale swam past the boat."),
    ("Tiny", "Miniature", "Enormous", "Colossal", "Huge", "The miniature car fits in my hand."),
    ("Fatigue", "Tiredness", "Energy", "Vigor", "Strength", "She felt a lot of tiredness after the long run."),
    ("Energy", "Vigor", "Fatigue", "Weakness", "Lethargy", "He tackled the project with great vigor."),
    ("Generous", "Unselfish", "Greedy", "Selfish", "Stingy", "It was unselfish of her to share her lunch."),
    ("Greedy", "Selfish", "Generous", "Giving", "Kind", "The selfish boy kept all the toys to himself."),
    ("Hazard", "Danger", "Safety", "Security", "Protection", "The icy stairs are a danger to everyone."),
    ("Safety", "Security", "Hazard", "Risk", "Peril", "Security is important at the airport."),
    ("Ignore", "Neglect", "Notice", "Observe", "Watch", "You should not neglect your homework."),
    ("Notice", "Observe", "Ignore", "Overlook", "Miss", "Did you observe how the birds built their nest?"),
    ("Jovial", "Cheerful", "Gloomy", "Sad", "Miserable", "The cheerful girl brightened everyone's day."),
    ("Gloomy", "Miserable", "Jovial", "Joyful", "Happy", "The miserable weather kept us indoors."),
    ("Keen", "Eager", "Reluctant", "Apathetic", "Bored", "He is eager to learn how to swim."),
    ("Reluctant", "Hesitant", "Keen", "Willing", "Eager", "She was hesitant to try the spicy food."),
    ("Lucid", "Clear", "Confusing", "Muddled", "Fuzzy", "The teacher gave a clear explanation."),
    ("Confusing", "Muddled", "Lucid", "Clear", "Obvious", "The muddled instructions were hard to follow."),
    ("Magnify", "Enlarge", "Shrink", "Reduce", "Decrease", "You can enlarge the picture on your computer."),
    ("Shrink", "Reduce", "Magnify", "Expand", "Grow", "Washing the sweater in hot water will reduce its size."),
    ("Nimble", "Agile", "Clumsy", "Awkward", "Slow", "The agile cat jumped gracefully onto the fence."),
    ("Clumsy", "Awkward", "Nimble", "Graceful", "Agile", "The awkward puppy kept tripping over its own feet."),
    ("Obey", "Comply", "Defy", "Rebel", "Resist", "You must comply with the rules of the game."),
    ("Defy", "Resist", "Obey", "Submit", "Follow", "It is dangerous to resist the police officers."),
    ("Praise", "Compliment", "Criticize", "Insult", "Blame", "She gave him a nice compliment on his work."),
    ("Criticize", "Blame", "Praise", "Commend", "Applaud", "It is not helpful to blame others for your mistakes."),
    ("Quaint", "Charming", "Modern", "Ordinary", "Ugly", "The charming cottage had a thatched roof."),
    ("Modern", "Contemporary", "Quaint", "Traditional", "Old-fashioned", "The contemporary art museum had many new exhibits."),
    ("Radiant", "Shining", "Dull", "Dim", "Gloomy", "The shining sun warmed the beach."),
    ("Dull", "Bleak", "Radiant", "Bright", "Luminous", "The bleak winter landscape looked gray and cold."),
    ("Sincere", "Honest", "Fake", "Deceitful", "Phony", "He made an honest apology for breaking the window."),
    ("Fake", "Deceitful", "Sincere", "Genuine", "Real", "The deceitful salesperson tricked the customers."),
    ("Timid", "Shy", "Bold", "Brave", "Confident", "The shy little boy hid behind his mother."),
    ("Bold", "Confident", "Timid", "Fearful", "Afraid", "She was confident in her ability to win the race."),
    ("Unique", "Distinctive", "Common", "Ordinary", "Normal", "The distinctive bird had bright blue feathers."),
    ("Common", "Ordinary", "Unique", "Rare", "Unusual", "A pigeon is an ordinary sight in the city."),
    ("Vast", "Immense", "Tiny", "Small", "Limited", "The immense ocean stretched as far as the eye could see."),
    ("Tiny", "Minute", "Vast", "Colossal", "Giant", "The minute detail could only be seen with a microscope."),
    ("Wise", "Sensible", "Foolish", "Silly", "Stupid", "It is sensible to save your money for the future."),
    ("Foolish", "Silly", "Wise", "Prudent", "Smart", "It was silly of him to ignore the warning signs."),
    ("Yield", "Surrender", "Resist", "Fight", "Defend", "The army had to surrender after running out of supplies."),
    ("Resist", "Fight", "Yield", "Submit", "Give in", "They will fight to protect their homeland.")
]

HARD_WORDS = [
    ("Abundant", "Plentiful", "Scarce", "Rare", "Lack", "The plentiful harvest ensured no one went hungry."),
    ("Scarce", "Rare", "Abundant", "Common", "Copious", "The rare stamp was worth a lot of money."),
    ("Benevolent", "Kind", "Cruel", "Malicious", "Mean", "The kind stranger helped the lost child find his way home."),
    ("Malicious", "Cruel", "Benevolent", "Charitable", "Kind", "The cruel king ruled with an iron fist."),
    ("Candid", "Frank", "Deceptive", "Guarded", "Secretive", "She was frank about her opinions on the matter."),
    ("Deceptive", "Misleading", "Candid", "Open", "Honest", "The misleading advertisement tricked many people."),
    ("Diligent", "Studious", "Lazy", "Idle", "Negligent", "The studious student spent hours in the library."),
    ("Lazy", "Idle", "Diligent", "Industrious", "Active", "The idle man sat on the porch all day."),
    ("Eloquent", "Articulate", "Inarticulate", "Mumbling", "Stuttering", "The articulate speaker captivated the audience."),
    ("Inarticulate", "Mumbling", "Eloquent", "Fluent", "Expressive", "He was mumbling so softly no one could hear him."),
    ("Frivolous", "Trivial", "Serious", "Important", "Crucial", "They wasted time arguing over trivial details."),
    ("Crucial", "Important", "Frivolous", "Silly", "Minor", "It is important to study for the final exam."),
    ("Gargantuan", "Colossal", "Minuscule", "Microscopic", "Tiny", "The colossal statue dwarfed everything around it."),
    ("Minuscule", "Microscopic", "Gargantuan", "Titanic", "Massive", "The microscopic organisms are visible only under a lens."),
    ("Haughty", "Arrogant", "Humble", "Modest", "Meek", "The arrogant prince demanded everyone bow to him."),
    ("Humble", "Modest", "Haughty", "Conceited", "Proud", "The modest scientist downplayed her groundbreaking discovery."),
    ("Impeccable", "Flawless", "Defective", "Faulty", "Imperfect", "Her flawless performance earned a standing ovation."),
    ("Defective", "Faulty", "Impeccable", "Perfect", "Unblemished", "The faulty brakes caused the car to crash."),
    ("Jubilant", "Ecstatic", "Sorrowful", "Depressed", "Sad", "The ecstatic fans rushed the field after the victory."),
    ("Sorrowful", "Depressed", "Jubilant", "Elated", "Overjoyed", "He felt depressed after receiving the bad news."),
    ("Kinship", "Affinity", "Enmity", "Hostility", "Hatred", "He felt a strong affinity for the stray dog."),
    ("Enmity", "Hostility", "Kinship", "Connection", "Bond", "There was deeply-rooted hostility between the two rival families."),
    ("Luminous", "Radiant", "Murky", "Gloomy", "Dark", "The radiant moon lit up the dark night sky."),
    ("Murky", "Gloomy", "Luminous", "Brilliant", "Shining", "The gloomy forest was filled with shadows."),
    ("Meticulous", "Painstaking", "Careless", "Sloppy", "Messy", "The painstaking research took years to complete."),
    ("Careless", "Sloppy", "Meticulous", "Thorough", "Precise", "His sloppy handwriting was difficult to read."),
    ("Notorious", "Infamous", "Renowned", "Famous", "Celebrated", "The infamous outlaw was feared throughout the land."),
    ("Renowned", "Famous", "Notorious", "Disreputable", "Scandalous", "The famous actor was recognized everywhere he went."),
    ("Opulent", "Luxurious", "Destitute", "Penniless", "Poor", "The luxurious mansion featured marble floors and crystal chandeliers."),
    ("Destitute", "Penniless", "Opulent", "Lavish", "Wealthy", "The penniless beggar sat on the cold street corner."),
    ("Plausible", "Credible", "Inconceivable", "Unlikely", "Impossible", "The detective found the suspect's alibi to be credible."),
    ("Inconceivable", "Unlikely", "Plausible", "Probable", "Believable", "It is unlikely that it will snow in the desert today."),
    ("Quintessential", "Typical", "Atypical", "Unusual", "Rare", "The apple pie is a typical American dessert."),
    ("Atypical", "Unusual", "Quintessential", "Classic", "Standard", "An unusual painting caught her eye at the gallery."),
    ("Resilient", "Tenacious", "Fragile", "Vulnerable", "Weak", "The tenacious weeds grew back quickly despite being pulled."),
    ("Fragile", "Vulnerable", "Resilient", "Strong", "Tough", "The vulnerable hatchlings needed protection from predators."),
    ("Superfluous", "Excessive", "Essential", "Necessary", "Vital", "The excessive amount of salt made the soup inedible."),
    ("Essential", "Necessary", "Superfluous", "Redundant", "Extra", "Water is necessary for survival."),
    ("Trepidation", "Apprehension", "Composure", "Confidence", "Calmness", "She viewed the upcoming recital with apprehension."),
    ("Composure", "Confidence", "Trepidation", "Dread", "Fear", "He spoke with confidence during the important meeting."),
    ("Ubiquitous", "Omnipresent", "Rare", "Scarce", "Uncommon", "Cell phones are virtually omnipresent in modern society."),
    ("Rare", "Uncommon", "Ubiquitous", "Pervasive", "Widespread", "The uncommon bird species was difficult to find in the wild."),
    ("Vociferous", "Clamorous", "Subdued", "Quiet", "Silent", "The clamorous crowd demanded to be heard."),
    ("Subdued", "Quiet", "Vociferous", "Boisterous", "Loud", "The quiet child preferred to read alone in the corner."),
    ("Waning", "Declining", "Waxing", "Growing", "Expanding", "His declining health worried his family."),
    ("Waxing", "Growing", "Waning", "Fading", "Decreasing", "The growing tree provided more shade each year."),
    ("Zealous", "Fervent", "Apathetic", "Indifferent", "Uncaring", "The fervent supporters cheered passionately for their candidate."),
    ("Apathetic", "Indifferent", "Zealous", "Enthusiastic", "Passionate", "He felt indifferent about which movie they chose to watch.")
]

def get_synonym_questions(level, num_questions=10):
    if level == "Easy":
        data = EASY_WORDS
    elif level == "Medium":
        data = MEDIUM_WORDS
    else:
        data = HARD_WORDS
    
    # Randomly select num_questions so they don't repeat in a session
    selected = random.sample(data, min(num_questions, len(data)))
    
    questions = []
    for w, c, w1, w2, w3, ex in selected:
        opts = [c, w1, w2, w3]
        random.shuffle(opts)
        questions.append({
            "word": w,
            "correct": c,
            "options": opts,
            "explanation": ex
        })
    return questions
